name: Sonoma County Shade Co.
favicon: null
layout_spectrum: 0.5203880115877837
typography_spectrum: 0.7850012197159231
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.4840797744691372
  lightness: 0.9949027139227837
  saturation: 0.9693252961151302
  rhythmicContrast: 0.015490437392145395
purpose:
  - name: sign-ups
    item: null
    url: null
