name: null
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75984
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#93d282'
    - '#000000'
    - '#6f6f6f'
    - '#2d2d2d'
  brandStrength: 0
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.75
purpose:
  - name: sign-ups
    item: null
    url: null
