name: Sonoma County Shade Co.
favicon: null
layout_spectrum: 0.7900757160969079
typography_spectrum: 0.22802199725992978
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#96CA2D'
    - '#B5E655'
    - '#EDF7F2'
    - '#4BB5C1'
    - '#7FC6BC'
  brandStrength: 0.2752647192683071
  lightness: 0.8796678367070854
  saturation: 0.2360990704037249
  rhythmicContrast: 0.8362571757752448
purpose:
  - name: sign-ups
    item: null
    url: null
